var khachhangController = require('../controllers/khachhang.controller');
var express = require('express');
var router = express.Router();
const authMiddleware = require('../middleware/auth.midddleware');
router.get('/list',authMiddleware.LoginRequire, khachhangController.getListKH);
router.get('/add',authMiddleware.LoginRequire, khachhangController.getAddKH);
router.post('/add',authMiddleware.LoginRequire, khachhangController.postAddKH);
router.get('/edit:id',authMiddleware.LoginRequire, khachhangController.getEditKH);
router.post('/edit:id',authMiddleware.LoginRequire, khachhangController.postEditKH);
router.get('/delete:id',authMiddleware.LoginRequire, khachhangController.getDeleteKH);
router.post('/delete:id',authMiddleware.LoginRequire, khachhangController.postDeleteKH);
module.exports = router;